name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  Preparation:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13.2
        env:
          POSTGRES_USER: ${{secrets.PG_USERNAME}}
          POSTGRES_PASSWORD: ${{secrets.PG_PASSWORD}}
        ports: ['5432:5432']

    steps:
      - uses: actions/checkout@master

      - name: Setup Ruby 3.0.1
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.1

      - name: Setup Node 14
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache yarn
        uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Cache gems
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gem-
      - name: Install dependencies
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
          yarn install --frozen-lockfile
      - name: DB create Migrate
        env:
          DATABASE_URL: ${{secrets.DATABASE_URL}}
        run: |
          bundle exec rails db:schema:load
      
  Deploy:
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
    needs: Preparation
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Deploy To Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "proten" 
          heroku_email: "codeponpon@gmail.com"
        env:
          RAILS_MASTER_KEY: ${{secrets.RAILS_MASTER_KEY}}
          DATABASE_URL: ${{secrets.DATABASE_URL}} 
          HOST: https://proten.herokuapp.com